name: TTLock2MQTT
version: "0.7"
slug: ttlock2mqtt
description: Connection between TTLock devices with Home Assistant using MQTT
url: "https://github.com/MatterVN/TTLock2MQTT"
arch: 
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: auto
services:
  - "mqtt:need"
options:
  State_delay: 60
  Battery_delay: 300
  Log_level: "INFO"
schema:
  TTLock_username: "str"
  TTLock_password: "password"
  TTLock_client_Id: "str"
  TTLock_client_secrect: "str"
  Log_level: "list(DEBUG|INFO|WARNING|ERROR)"
  State_delay: "int(10,3600)"
  Battery_delay: "int(10,3600)"
  Max_threads: "int?"